server/config/routes.rb
Basic::Application.routes.draw do
  root :to => 'demo#index'
  get 'demo/fetch'
  get 'demo/autoupload'
  get 'demo/optimization'
  get 'demo/aesthetics'
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

server/app/controllers/demo_controller.rb
class DemoController < ApplicationController

  before_action :check_configuration

  def check_configuration
    render 'configuration_missing' if Cloudinary.config.api_key.blank?
  end

  def index
    # First, upload local or remote images to Cloudinary.
    # For the purposes of the demo, we do it on each request
    # to keep things simple.
    upload_images
    
    # We can now display the uploaded images and apply transformations on them.
    render
  end
  def fetch
    render
  end
  def autoupload
    render
  end
  def optimization
    render
  end
  def aesthetics
    render
  end

  private

  def local_image_path(name)
    Rails.root.join('uploads', name).to_s
  end

  def upload_images
    @uploads = {}


    # create https urls for each public id
    @uploads[:dog] = Cloudinary::Utils.cloudinary_url("dog.jpg", :width=>300,:crop => :scale, :secure=>true)
    @uploads[:faces] = Cloudinary::Utils.cloudinary_url("faces.jpeg", :width=>300, :crop => :scale,:secure=>true)
    @uploads[:face] = Cloudinary::Utils.cloudinary_url("face.jpeg", :width=>300, :crop => :scale,:secure=>true)
    @uploads[:logo] = Cloudinary::Utils.cloudinary_url("logo.png", :width => 300,:crop => :scale, :secure=>true)
    @uploads[:video] = Cloudinary::Utils.cloudinary_url("video",  :width => 300,:crop => :scale,:secure=>true, :resource_type=>:video)
 

    
      puts JSON.pretty_generate(@uploads[:dog]) 
      puts JSON.pretty_generate(@uploads[:faces]) 
      puts JSON.pretty_generate(@uploads[:logo]) 
      puts JSON.pretty_generate(@uploads[:video]) 



  end

end

server/app/views/demo/_image_box.html.erb
<div class="item">

<div class="caption">
 <%= description %>
</div>

<% options_with_format = options.merge(:format => format) %>
  <%= cl_image_tag(public_id, options_with_format) %>
  <div class="link">
    <% link_url = cloudinary_url(public_id, options_with_format) %>
    <%= link_to(link_url, link_url, :target => '_blank') %>
    <p> <%= "#{options_with_format}" %>
  </div>

  

</div>

server/app/views/demo/_video_box.html.erb
<div class="item">

<div class="caption">
 <%= description %>
</div>

<% options_with_controls = options.merge(:controls => true, :resource_type => 'video') %>
<%= cl_video_tag(public_id, options_with_controls) %>
<div class="link">
  <% link_url = cloudinary_url(public_id, options) %>
  <%= link_to(link_url, link_url, :target => '_blank') %>
  <p> <%= "#{options_with_controls}" %>
</div>

  

</div>

server/app/views/demo/aesthetics.html.erb
<h1>
  Aesthetic Transformations
</h1>

<h3>Radius (rounded corners)</h3>
<%= render 'image_box',
  public_id: 'face',
  format: '',
  description: 'face Height 300, Width 300, Crop thumb,  Format auto, Quality auto , radius max',
  options: { width: 300, height: 300, crop: "thumb", 
  gravity: "auto", fetch_format: "auto" , quality: "auto",
  radius: "max"}
%>

<h3>Borders</h3>

<%= render 'image_box',
  public_id: 'face',
  format: '',
  description: 'face Height 300, Width 300, Crop thumb,  Format auto, Quality auto , radius max, border',
  options: { width: 300, height: 300, crop: "thumb", 
  gravity: "auto", fetch_format: "auto" , quality: "auto",
  radius: "max",
  border: "10px_solid_rgb:bde4fb"}
%>

<h3>Background Color</h3>

<!--  use a crop pad to leave some space to show background -->
<%= render 'image_box',
  public_id: 'face',
  format: '',
  description: 'face Height 300, Width 200, Crop pad,  Format auto, Quality auto, border',
  options: { width: 300, height: 200, crop: "pad", 
  fetch_format: "auto" , quality: "auto",
  background: "red"}
%>

<!-- look at predominant, also try predominant_contrast, border, border_contrast -->
<%= render 'image_box',
  public_id: 'face',
  format: '',
  description: 'face Height 300, Width 200, Crop pad,  Format auto, Quality auto, border auto',
  options: { width: 300, height: 200, crop: "pad", 
  fetch_format: "auto" , quality: "auto",
  background: "auto:predominant"}
%>


<h3>Effects and Filters</h3>

<h4>Outline Effect</h4>
<%= render 'image_box',
  public_id: 'dog',
  format: '',
  description: 'dog Height 300, Width 300, Crop thumb, Format auto, Quality auto, effect outline orange',
  options: { width: 300, height: 300, crop: "thumb",
  gravity: "face", fetch_format: "auto" , quality: "auto",
  effect: "outline:15:200", color: "orange"}
%>

<h4>Improve Effect</h4>
<%= render 'image_box',
  public_id: 'dog',
  format: '',
  description: 'dog Height 300, Width 300, Crop thumb, Format auto, Quality auto, effect improve',
  options: { width: 300, height: 300, crop: "thumb",
  gravity: "face", fetch_format: "auto" , quality: "auto",
  effect: "improve"}
%>

<!-- try other art effects like  daguerre, quartz, linen, incognito-->
<h4>Art Filters</h4>
<%= render 'image_box',
  public_id: 'dog',
  format: '',
  description: 'dog Height 300, Width 300, Crop thumb, Format auto, Quality auto, effect art',
  options: { width: 300, height: 300, crop: "thumb",
  fetch_format: "auto" , quality: "auto",
  effect: "art:zorro"}
%>
<h4>Cartoonify Filters</h4>
<%= render 'image_box',
  public_id: 'face',
  format: '',
  description: 'faces Height 300, Width 300, Crop thumb, Format auto, Quality auto, effect cartoonify',
  options: { width: 300, height: 300, crop: "thumb",
  gravity: "face", fetch_format: "auto" , quality: "auto",
  effect: "cartoonify"}
%>
<h4>Color tint</h4>
<%= render 'image_box',
  public_id: 'face',
  format: '',
  description: 'faces Height 300, Width 300, Crop thumb, Format auto, Quality auto, effect tint ',
  options: { width: 300, height: 300, crop: "thumb",
  gravity: "face", fetch_format: "auto" , quality: "auto",
  effect: "tint:50:blue"}
%>

<h3>Overlay</h3>

<!-- overlays are chained transformations so you need an array -->
<h4>Image over Image</h4>
<%= render 'image_box',
  public_id: 'face',
  format: '',
  description: 'faces Height 300, Width 300, Crop thumb,  logo overlay ',
  options: { :transformation=>[
    {width: 300, height: 300, crop: "thumb",gravity: "auto"},
    {overlay: "logo", width: 100, height: 100, crop: "thumb",gravity:"south_east"}
  ]
  }
%>

<h4>Text over Image</h4>
<%= render 'image_box',
  public_id: 'faces',
  format: '',
  description: 'faces Height 300, Width 300, Crop thumb,  text overlay ',
  options: { transformation: [
    {width: 300, height: 300, crop: "thumb"},
    {overlay: {font_family: "Arial", font_size: 30, text: "Tutoring"}, 
    background: "white", color: "red", gravity: "north_west", y:10, x:10}
  ]
  }
%>

<!-- thumb doesn't work for video -->
<h4>Image over Video</h4>
<%= render 'video_box',
  public_id: 'video',
  description: 'faces Width 300, Crop scale, logo overlay ',
  options: { transformation: [
    {width: 300, crop: "scale"},
    {overlay: "logo", width: 50, height: 50, crop: "thumb",gravity:"south_east"}
  ]
  }
%>

<h4>Text over Video</h4>
<%= render 'video_box',
  public_id: 'video',
  description: 'faces Width 300, Crop scale, text overlay ',
   options: { transformation: [
    {width: 300, crop: "scale"},
    {overlay: {font_family: "Arial", font_size:30, text:"Earth"}, 
    background:"white", color:"blue", gravity:"north_west", y:10, x:10}
   ]
   }
%>


server/app/views/demo/autoupload.html.erb
<h1>Auto-upload Examples</h1>

<p>Need to map a folder named 'remote-media` to a cloudinary training server 
path `https://cloudinary-training.github.io/cld-advanced-concepts/assets/` in the DAM.
<br>
You can access the following assets:
  <ul>
    <li><a href="https://cloudinary-training.github.io/cld-advanced-concepts/assets/images/dolphin.jpg" target="_blank">images/dolphin.jpg</a></li>
    <li>video/snowboarding.mp4</li>
    <li>raw/data.json</li>
  </ul>
</p>

<!-- image example -->
<%= render 'image_box',
  public_id: 'remote-media/images/dolphin',
  description: 'Auto-upload image from remote',
  format: '',
  options: {width: 300, height: 300, crop: "lpad"}
%>

<!-- video example -->
<%= render 'video_box',
  public_id: 'remote-media/video/snowboarding',
  description: 'Auto-upload image from remote',
  options: {width: 300, crop: "scale"}
%>

<!-- raw example -->

 <%= link_to(
    cloudinary_url('remote-media/raw/data.json',{:type => 'upload', :resource_type => 'raw'}), 
    cloudinary_url('remote-media/raw/data.json',{:type => 'upload', :resource_type => 'raw'}), 
    :target => '_blank') 
%>

server/app/views/demo/configuration_missing.html.erb
<div>
  <h1>
    Missing cloudinary.yml
  </h1>
  <p>
    You will need a Cloudinary account to run this demo project.
    <ol>
      <li>
        If you don't have an account, sign up for free
        <%= link_to 'here', 'https://cloudinary.com/users/register/free' %>.
      </li>
      <li>
        Download your customized cloudinary.yml configuration file using our
        <%= link_to 'Management Console', 'https://cloudinary.com/console' %>
        or by following this
        <%= link_to 'direct link', 'http://cloudinary.com/console/cloudinary.yml' %>.
      </li>
      <li>
        Place cloudinary.yml into the project's config directory.
      </li>
      <li>
        Restart your Rails server process.
      </li>
    </ol>
  </p>
</div>

server/app/views/demo/fetch.html.erb
<h1>Fetch Examples</h1>

<p>Need to unrestrict in security settings</p>
<%= render 'image_box',
  public_id: 'https://cdn.pixabay.com/photo/2015/03/26/09/39/cupcakes-690040__480.jpg',
  description: 'Fetch image from remote ',
  format: '',
  options: {type: 'fetch'}
%>

server/app/views/demo/index.html.erb
<h1>
  Generating URL with Helpers (image, video, URL)
</h1>


<!-- scaling takes place in the demo_controller -->
<h2>Original Assets</h2>
<h3>Scaled to 300px</h3>

<p>dog</p>
<%= image_tag(@uploads[:dog]) %>
<div class="link">
  <%= link_to(@uploads[:dog], @uploads[:dog], target: '_blank') %>
</div>
<p>face</p>
<%= image_tag(@uploads[:face]) %>
<div class="link">
  <%= link_to(@uploads[:face], @uploads[:face], target: '_blank') %>
</div>
<p>faces</p>
<%= image_tag(@uploads[:faces]) %>
<div class="link">
  <%= link_to(@uploads[:faces], @uploads[:faces], target: '_blank') %>
</div>
<p>logo</p>
<%= image_tag(@uploads[:logo]) %>
<div class="link">
  <%= link_to(@uploads[:logo], @uploads[:logo], target: '_blank') %>
</div>
<p>video</p>
<%= cl_video_tag(@uploads[:video], controls: true) %>
<div class="link">
  <%= link_to(@uploads[:video], @uploads[:video], target: '_blank') %>
</div>





server/app/views/demo/optimization.html.erb
<h1>Optimization</h1>

<% if false %>
<h3>Crop Dog</h3>
<!-- cropping takes a chunk out of an image -->
<%= render 'image_box',
  public_id: 'dog',
  format: 'jpg',
  description: 'dog Width 300, Height 200,Crop crop',
  options: { width: 300, height: 200, crop: "crop" }
%>


<h3>Thumb Dog with Gravity</h3>
<!-- use gravity with thumb to get focus on someting interesting or a compass point -->
<%= render 'image_box',
  public_id: 'dog',
  format: 'jpg',
  description: 'dog Width 300, Height 200,Crop thumb, Gravity auto',
  options: { width: 300, height: 200, crop: "thumb", gravity: "auto" }
%>

<h3>Thumb Face with Gravity</h3>
<%= render 'image_box',
  public_id: 'face',
  format: 'jpeg',
  description: 'face Width 300, Height 200,Crop thumb, Gravity face',
  options: { width: 300, height: 200, crop: "thumb", gravity: "face" }
%>
<h3>Thumb Faces with Gravity</h3>
<%= render 'image_box',
  public_id: 'faces',
  format: 'jpeg',
  description: 'faces Width 300, Height 200,Crop thumb, Gravity faces',
  options: { width: 300, height: 200, crop: "thumb", gravity: "faces" }
%>

<h3>Thumb Logo with Fill</h3>
<!-- you don't have to use gravity if not needed - fill gives exact dimensions-->
<%= render 'image_box',
  public_id: 'logo',
  format: 'png',
  description: 'logo Width 100, Height 100,Crop fill',
  options: { width: 100, height: 100, crop: "fill" }
%>

<h2>Format</h2>
<!--let Cloudinary determine the best format base on browser -->
<%= render 'image_box',
  public_id: 'dog',
  format: '',
  description: 'dog Height 300, Crop scale,  Format auto ',
  options: { height: 300, crop: "scale", fetch_format: "auto" }
%>

<h2>Quality (Compression)</h2>

<!--let Cloudinary determine quality ~80 or you can supply a number from 1-100 -->
<%= render 'image_box',
  public_id: 'faces',
  format: '',
  description: 'faces Height 300, Crop scale,  Format auto, Quality auto ',
  options: { height: 300, crop: "scale", fetch_format: "auto" , quality: "auto"}
%>

<% end %>

server/app/views/demo/snippent.erb
<% options_with_format = options.merge(:format => 'jpg') %>
  <%= cl_image_tag(public_id, options_with_format) %>
  <div class="link">
    <% link_url = cloudinary_url(public_id, options_with_format) %>
    <%= link_to(link_url, link_url, :target => '_blank') %>
  </div>

 <%= image_tag(url) %>
  <div class="link">
    <%= link_to(url, url, :target => '_blank') %>
  </div>

  <div class="caption">
    <%= description %>
  </div>

  <div class="public_id">
  Image Public ID:
  <%= public_id %>
</div>

  
<!--<%= render 'image_box',
  :upload => @uploads[:pizza2],
  :description => 'Fit into 200x150',
  :options => { :width => 200, :height => 150, :crop => "fit" }
%> -->

<%= render 'image_box',
  :public_id => 'dog',
  :format => 'jpg',
  :description => 'dog Width 200',
  :options => { :width => 200, :height => 200, :crop => "fill" }
%>

<%= render 'image_box',
  :public_id => 'faces',
   :format => 'jpg',
  :description => 'Fill 200x200',
  :options => { :width => 200, :height => 200, :crop => "fill" }
%>

<%= render 'image_box',
  :public_id => 'logo',
   :format => 'png',
  :description => 'Fill 200x200',
  :options => { :width => 200, :height => 200, :crop => "fill" }
%>

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cloudinary Training</title>
  <%= stylesheet_link_tag "demo", :media => "all" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<nav>

  <ul>
    <li><%= link_to 'Home', root_path%></li>
    <li><%= link_to 'Optimization', demo_optimization_path%>
    </li>
    <li><%= link_to 'Aesthetics', demo_aesthetics_path%>
    </li>
    <li><%= link_to 'Fetch', demo_fetch_path%>
    </li>
    <li><%= link_to 'Auto-upload', demo_autoupload_path%>
  </li>

  </ul>

</nav>

<%= yield %>

</body>
</html>